# TOP LEVEL CONFIGURATION
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]

#########################################################
# RESET INTERFACE (NOTE This is on Bank 34, you may need to adjust it)
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
#This net is actively driven on the SOM
#set_property PULLUP true [get_ports sys_rst_n]

#########################################################
# GPMC interface

# standards
set_property IOSTANDARD LVCMOS18 [get_ports i_gpmc_cs_n]
set_property IOSTANDARD LVCMOS18 [get_ports i_gpmc_adv_n]
set_property IOSTANDARD LVCMOS18 [get_ports i_gpmc_oe_n]
set_property IOSTANDARD LVCMOS18 [get_ports i_gpmc_we_n]
set_property IOSTANDARD LVCMOS18 [get_ports {i_gpmc_be_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_gpmc_be_n[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpmc_ad[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_sys_nirq[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_sys_nirq[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_gpmc_clk}]

#############################################################
# VIDEO INTERFACE
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {o_vin_d[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports o_vin_clk]

#############################################################
# FPIO IO connections (GPIO for devkit example)
# Pin Assignments from spreadsheet

# NOTE the voltage standard set here is 1.8V, but these 
# pins are attached to Banks 15 or 34, which have
# external connections for the bank voltage.  You need
# to set these voltage levels accordingly.
set_property IOSTANDARD LVCMOS18 [get_ports {LA21_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA21_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA22_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA18_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA22_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA18_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA19_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA23_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA19_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA23_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA20_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA14_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA20_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA14_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA17_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA15_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA17_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA15_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA16_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA16_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA10_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA13_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA13_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA12_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA06_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA06_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA09_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA07_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA09_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA07_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA08_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA02_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA08_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA02_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA04_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA05_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA04_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA05_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA03_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA00_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA03_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA00_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA01_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA01_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA12_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA13_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA28_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA13_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA28_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA08_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA26_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA08_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA26_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA09_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA31_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA09_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA31_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA27_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA07_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA27_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA07_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA04_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA30_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA04_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA30_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA05_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA25_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA05_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA25_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA33_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA33_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA24_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA10_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA24_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA02_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA32_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA02_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA32_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA03_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA29_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA03_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LA29_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA06_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA00_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA06_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA00_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA01_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {HA01_N}]
# bank 34
set_property IOSTANDARD LVCMOS18 [get_ports {o_cpu_nmi_n}]
# bank 15
set_property IOSTANDARD LVCMOS18 [get_ports {i_id[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {i_id[1]}]
