
###################################################
# PCI EXPRESS INTERFACE (see also xilinx_pcie_7x_ep_x2g2.xdc)
# PCIe on clock 0 and data pairs 0/1
set_property PACKAGE_PIN E3 [get_ports {pci_exp_rxn[1]}]
set_property PACKAGE_PIN E4 [get_ports {pci_exp_rxp[1]}]
set_property PACKAGE_PIN H1 [get_ports {pci_exp_txn[1]}]
set_property PACKAGE_PIN H2 [get_ports {pci_exp_txp[1]}]
set_property PACKAGE_PIN A3 [get_ports {pci_exp_rxn[0]}]
set_property PACKAGE_PIN A4 [get_ports {pci_exp_rxp[0]}]
set_property PACKAGE_PIN F1 [get_ports {pci_exp_txn[0]}]
set_property PACKAGE_PIN F2 [get_ports {pci_exp_txp[0]}]

set_property PACKAGE_PIN B5 [get_ports sys_clk_n]
set_property PACKAGE_PIN B6 [get_ports sys_clk_p]
set_property PACKAGE_PIN R6 [get_ports sys_rst_n]
set_property LOC IPAD_X1Y17 [get_ports sys_clk_n]
set_property LOC IPAD_X1Y16 [get_ports sys_clk_p]

# PCIe on clock 1 and data pairs 2/3
#set_property PACKAGE_PIN G3 [get_ports {pci_exp_rxn[0]}]
#set_property PACKAGE_PIN G4 [get_ports {pci_exp_rxp[0]}]
#set_property PACKAGE_PIN B1 [get_ports {pci_exp_txn[0]}]
#set_property PACKAGE_PIN B2 [get_ports {pci_exp_txp[0]}]
#set_property PACKAGE_PIN C3 [get_ports {pci_exp_rxn[1]}]
#set_property PACKAGE_PIN C4 [get_ports {pci_exp_rxp[1]}]
#set_property PACKAGE_PIN D1 [get_ports {pci_exp_txn[1]}]
#set_property PACKAGE_PIN D2 [get_ports {pci_exp_txp[1]}]
#set_property PACKAGE_PIN D5 [get_ports sys_clk_n]
#set_property PACKAGE_PIN D6 [get_ports sys_clk_p]

#########################################################
# GPMC interface
# locations
# CONFIG -> CSI_B
set_property PACKAGE_PIN T17 [get_ports i_gpmc_cs_n]
# CONFIG -> RDWR
set_property PACKAGE_PIN R18 [get_ports i_gpmc_oe_n]
# CONFIG -> CCLK Must be doubled externally
# CONFIG -> EMCCLK
#set_property PACKAGE_PIN P15 [get_ports i_gpmc_clk]
set_property PACKAGE_PIN P15 [get_ports o_vin_hsync]
set_property PACKAGE_PIN K18 [get_ports i_gpmc_we_n]
# D0->D16
set_property PACKAGE_PIN K16 [get_ports {io_gpmc_ad[0]}]
set_property PACKAGE_PIN L17 [get_ports {io_gpmc_ad[1]}]
set_property PACKAGE_PIN J15 [get_ports {io_gpmc_ad[2]}]
set_property PACKAGE_PIN J16 [get_ports {io_gpmc_ad[3]}]
set_property PACKAGE_PIN K17 [get_ports {io_gpmc_ad[4]}]
set_property PACKAGE_PIN L18 [get_ports {io_gpmc_ad[5]}]
set_property PACKAGE_PIN J14 [get_ports {io_gpmc_ad[6]}]
set_property PACKAGE_PIN K15 [get_ports {io_gpmc_ad[7]}]
set_property PACKAGE_PIN M15 [get_ports {io_gpmc_ad[8]}]
set_property PACKAGE_PIN M16 [get_ports {io_gpmc_ad[9]}]
set_property PACKAGE_PIN M17 [get_ports {io_gpmc_ad[10]}]
set_property PACKAGE_PIN M14 [get_ports {io_gpmc_ad[11]}]
set_property PACKAGE_PIN N14 [get_ports {io_gpmc_ad[12]}]
set_property PACKAGE_PIN N17 [get_ports {io_gpmc_ad[13]}]
set_property PACKAGE_PIN N18 [get_ports {io_gpmc_ad[14]}]
set_property PACKAGE_PIN P18 [get_ports {io_gpmc_ad[15]}]
#set_property PACKAGE_PIN L15 [get_ports i_gpmc_adv_n]
set_property PACKAGE_PIN L15 [get_ports o_vin_vsync]
set_property PACKAGE_PIN N16 [get_ports {i_gpmc_be_n[0]}]
set_property PACKAGE_PIN L14 [get_ports {i_gpmc_be_n[1]}]

# Interrupt interface
set_property PACKAGE_PIN J18 [get_ports {o_sys_nirq[0]}]
set_property PACKAGE_PIN U10 [get_ports {o_sys_nirq[1]}]
set_property PACKAGE_PIN J6  [get_ports {o_cpu_nmi_n}]

#############################################################
# VIDEO INTERFACE
set_property PACKAGE_PIN V16 [get_ports {o_vin_d[0]}]
set_property PACKAGE_PIN V17 [get_ports {o_vin_d[1]}]
set_property PACKAGE_PIN U16 [get_ports {o_vin_d[2]}]
set_property PACKAGE_PIN U17 [get_ports {o_vin_d[3]}]
set_property PACKAGE_PIN R16 [get_ports {o_vin_d[4]}]
set_property PACKAGE_PIN T18 [get_ports {o_vin_d[5]}]
set_property PACKAGE_PIN R17 [get_ports {o_vin_d[6]}]
set_property PACKAGE_PIN P16 [get_ports {o_vin_d[7]}]
set_property PACKAGE_PIN U12 [get_ports {o_vin_d[8]}]
set_property PACKAGE_PIN R15 [get_ports {o_vin_d[9]}]
set_property PACKAGE_PIN T14 [get_ports {o_vin_d[10]}]
set_property PACKAGE_PIN V13 [get_ports {o_vin_d[11]}]
set_property PACKAGE_PIN U15 [get_ports {o_vin_d[12]}]
set_property PACKAGE_PIN U14 [get_ports {o_vin_d[13]}]
set_property PACKAGE_PIN T15 [get_ports {o_vin_d[14]}]
set_property PACKAGE_PIN V14 [get_ports {o_vin_d[15]}]
set_property PACKAGE_PIN U9  [get_ports {o_vin_d[16]}]
set_property PACKAGE_PIN R13 [get_ports {o_vin_d[17]}]
set_property PACKAGE_PIN T12 [get_ports {o_vin_d[18]}]
set_property PACKAGE_PIN V9  [get_ports {o_vin_d[19]}]
set_property PACKAGE_PIN V11 [get_ports {o_vin_d[20]}]
set_property PACKAGE_PIN T13 [get_ports {o_vin_d[21]}]
set_property PACKAGE_PIN U11 [get_ports {o_vin_d[22]}]
set_property PACKAGE_PIN V12 [get_ports {o_vin_d[23]}]
set_property PACKAGE_PIN P14 [get_ports o_vin_clk]

#############################################################
# FPIO IO connections (GPIO for devkit example)
# Pin Assignments from spreadsheet
set_property PACKAGE_PIN A9 [get_ports {LA21_N}]
set_property PACKAGE_PIN B9 [get_ports {LA21_P}]
set_property PACKAGE_PIN A10 [get_ports {LA22_N}]
set_property PACKAGE_PIN A17 [get_ports {LA18_N}]
set_property PACKAGE_PIN B10 [get_ports {LA22_P}]
set_property PACKAGE_PIN B16 [get_ports {LA18_P}]
set_property PACKAGE_PIN C17 [get_ports {LA19_P}]
set_property PACKAGE_PIN B17 [get_ports {LA23_N}]
set_property PACKAGE_PIN C18 [get_ports {LA19_N}]
set_property PACKAGE_PIN C16 [get_ports {LA23_P}]
set_property PACKAGE_PIN D18 [get_ports {LA20_N}]
set_property PACKAGE_PIN D16 [get_ports {LA14_N}]
set_property PACKAGE_PIN E17 [get_ports {LA20_P}]
set_property PACKAGE_PIN E16 [get_ports {LA14_P}]
set_property PACKAGE_PIN F15 [get_ports {LA17_N}]
set_property PACKAGE_PIN E18 [get_ports {LA15_N}]
set_property PACKAGE_PIN G15 [get_ports {LA17_P}]
set_property PACKAGE_PIN F17 [get_ports {LA15_P}]
set_property PACKAGE_PIN F18 [get_ports {LA16_N}]
set_property PACKAGE_PIN G16 [get_ports {LA10_N}]
set_property PACKAGE_PIN G17 [get_ports {LA16_P}]
set_property PACKAGE_PIN H16 [get_ports {LA10_P}]
set_property PACKAGE_PIN H18 [get_ports {LA11_N}]
set_property PACKAGE_PIN C11 [get_ports {LA13_P}]
set_property PACKAGE_PIN H17 [get_ports {LA11_P}]
set_property PACKAGE_PIN B11 [get_ports {LA13_N}]
set_property PACKAGE_PIN C8 [get_ports {LA12_N}]
set_property PACKAGE_PIN A13 [get_ports {LA06_P}]
set_property PACKAGE_PIN D8 [get_ports {LA12_P}]
set_property PACKAGE_PIN A14 [get_ports {LA06_N}]
set_property PACKAGE_PIN A15 [get_ports {LA09_N}]
set_property PACKAGE_PIN A12 [get_ports {LA07_N}]
set_property PACKAGE_PIN B14 [get_ports {LA09_P}]
set_property PACKAGE_PIN B12 [get_ports {LA07_P}]
set_property PACKAGE_PIN B15 [get_ports {LA08_N}]
set_property PACKAGE_PIN C13 [get_ports {LA02_N}]
set_property PACKAGE_PIN C14 [get_ports {LA08_P}]
set_property PACKAGE_PIN D13 [get_ports {LA02_P}]
set_property PACKAGE_PIN D14 [get_ports {LA04_N}]
set_property PACKAGE_PIN C12 [get_ports {LA05_N}]
set_property PACKAGE_PIN E13 [get_ports {LA04_P}]
set_property PACKAGE_PIN D11 [get_ports {LA05_P}]
set_property PACKAGE_PIN F14 [get_ports {LA03_N}]
set_property PACKAGE_PIN C9 [get_ports {LA00_N}]
set_property PACKAGE_PIN G14 [get_ports {LA03_P}]
set_property PACKAGE_PIN D9 [get_ports {LA00_P}]
set_property PACKAGE_PIN D15 [get_ports {LA01_N}]
set_property PACKAGE_PIN V8 [get_ports {HA12_P}]
set_property PACKAGE_PIN E15 [get_ports {LA01_P}]
set_property PACKAGE_PIN V7 [get_ports {HA12_N}]
set_property PACKAGE_PIN U7 [get_ports {HA13_P}]
set_property PACKAGE_PIN R3 [get_ports {LA28_N}]
set_property PACKAGE_PIN V6 [get_ports {HA13_N}]
set_property PACKAGE_PIN T2 [get_ports {LA28_P}]
set_property PACKAGE_PIN M6 [get_ports {HA08_N}]
set_property PACKAGE_PIN R2 [get_ports {LA26_P}]
set_property PACKAGE_PIN N6 [get_ports {HA08_P}]
set_property PACKAGE_PIN R1 [get_ports {LA26_N}]
set_property PACKAGE_PIN P6 [get_ports {HA09_P}]
set_property PACKAGE_PIN J5 [get_ports {LA31_P}]
set_property PACKAGE_PIN P5 [get_ports {HA09_N}]
set_property PACKAGE_PIN J4 [get_ports {LA31_N}]
set_property PACKAGE_PIN P1 [get_ports {LA27_P}]
set_property PACKAGE_PIN T7 [get_ports {HA07_N}]
set_property PACKAGE_PIN N1 [get_ports {LA27_N}]
set_property PACKAGE_PIN R7 [get_ports {HA07_P}]
set_property PACKAGE_PIN T5 [get_ports {HA04_P}]
set_property PACKAGE_PIN K6 [get_ports {LA30_N}]
set_property PACKAGE_PIN R5 [get_ports {HA04_N}]
set_property PACKAGE_PIN K5 [get_ports {LA30_P}]
set_property PACKAGE_PIN U6 [get_ports {HA05_P}]
set_property PACKAGE_PIN L5 [get_ports {LA25_P}]
set_property PACKAGE_PIN U5 [get_ports {HA05_N}]
set_property PACKAGE_PIN M5 [get_ports {LA25_N}]
set_property PACKAGE_PIN V4 [get_ports {HA11_P}]
set_property PACKAGE_PIN M4 [get_ports {LA33_P}]
set_property PACKAGE_PIN U4 [get_ports {HA11_N}]
set_property PACKAGE_PIN N4 [get_ports {LA33_N}]
set_property PACKAGE_PIN L4 [get_ports {LA24_N}]
set_property PACKAGE_PIN T4 [get_ports {HA10_P}]
set_property PACKAGE_PIN L3 [get_ports {LA24_P}]
set_property PACKAGE_PIN T3 [get_ports {HA10_N}]
set_property PACKAGE_PIN N3 [get_ports {HA02_N}]
set_property PACKAGE_PIN M2 [get_ports {LA32_N}]
set_property PACKAGE_PIN N2 [get_ports {HA02_P}]
set_property PACKAGE_PIN M1 [get_ports {LA32_P}]
set_property PACKAGE_PIN V3 [get_ports {HA03_P}]
set_property PACKAGE_PIN P4 [get_ports {LA29_N}]
set_property PACKAGE_PIN V2 [get_ports {HA03_N}]
set_property PACKAGE_PIN P3 [get_ports {LA29_P}]
set_property PACKAGE_PIN U2 [get_ports {HA06_P}]
set_property PACKAGE_PIN K2 [get_ports {HA00_N}]
set_property PACKAGE_PIN U1 [get_ports {HA06_N}]
set_property PACKAGE_PIN K1 [get_ports {HA00_P}]
set_property PACKAGE_PIN K3 [get_ports {HA01_P}]
set_property PACKAGE_PIN L2 [get_ports {HA01_N}]
set_property PACKAGE_PIN D10 [get_ports {i_id[0]}]
set_property PACKAGE_PIN H14 [get_ports {i_id[1]}]

#############################################################
# ADC
set_property PACKAGE_PIN L9 [get_ports VN_0]
set_property PACKAGE_PIN K10 [get_ports VP_0]
